### ISSUE TITLE
Volatility?

### ISSUE THREAD

**Issue by Lakituthequick** [davidmz/apng-chrome#27]
I was looking through the code of this after a PHP script I made didn't work as it should.

That script returns some Cache-Control headers to prevent caching in order to make it work, but this plug-in actively rejects any images with any such headers. It does this with the `isVolatile` function.

I don't see the advantage of rejecting otherwise healthy images just because they prevent caching, so I'm wondering why this code exists?

**Comment by davidmz** [comment]
To process and show the image apng-chrome makes an additional HTTP request. If server returns "Cache-Conrol: no-cache" (or similar) header, then we can receive different image from request to request. And worse, each request may cause side-effects on server — CAPTCHA images is one of these cases. Early versions of apng-chrome (without this function) broke all PNG (not even APNG!) captchas. So now images with cache-preventing headers are not processed.

**Comment by Lakituthequick** [comment]
That makes sense, thanks.

Lets hope for the day that Chrome plug-ins can access (image) files without XHR then. :smiley:
