### ISSUE TITLE
Stopped working in Chromium 48

### ISSUE THREAD

**Issue by GwenDragon** [davidmz/apng-chrome#28]
The plugin stopped working in Chromium versions greater that 47.
It does not work: 

- Chromium 48.0.2564.82
- Chromium Dev 50.0.2625.0
- Vivaldi 1.0.385.5
- Opera Stable 35.0.2066.37
- Opera Dev 36.0.2120.0

The Error Console in Developer Tools shows:

content.js:93 
Uncaught TypeError: document.getCSSCanvasContext is not a function
getCanvasName @ content.js:93
(anonymous function) @ content.js:147
setStatus @ udeferred.js:32
deferred.resolve @ udeferred.js:54
execCall @ udeferred.js:103
execCall @ udeferred.js:100
execCall @ udeferred.js:100
setStatus @ udeferred.js:32
deferred.resolve @ udeferred.js:54
frame.img.onload @ apng-parser.js:180

**Comment by davidmz** [comment]
Chrome kill getCSSCanvasContext-technology in version 48. Unfortunately, it was critical part of this extension:( I looking for workaround, but not succeed yet.

**Comment by GabeEddyT** [comment]
I won't pretend to know the first thing about js but have you looked into [this](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/WvqvdsmiQzg)? 

> The CSS Houdini effort aims to provide a much better way to implement the same thing, via the Custom Paint feature. In addition, -webkit-canvas is non-standard, and many common use cases found are better implemented as SVG (see these examples of internal Chrome usage, for example).
...
Alternative implementation suggestion for web developers
Use SVG for static images. For dynamic ones, use transparency with a real canvas element behind the element.

**Comment by davidmz** [comment]
Of course, I've read about these technologies. Unfortunately, neither [Houdini](https://www.chromestatus.com/feature/5685444318593024) nor [element()](https://developer.mozilla.org/ru/docs/Web/CSS/element) are not supported on Chrome for now. As for SVG, the canvas is not shown inside the SVG, if SVG included as "img src", not opened as a separate document.

I have hopes for [canvas.toBlob](https://www.chromestatus.com/feature/4562033294966784), but it will be no earlier than the 50th version of Chrome.

**Comment by maxstepin** [comment]
Maybe, just maybe...

https://groups.google.com/d/topic/mozilla.dev.platform/0h_7GpOz1a0/discussion

**Comment by Raj9039852537** [comment]
A possible workaround is just to add getCSSCanvasContext method via js
and use that to load things up

**Comment by Raj9039852537** [comment]
[apng.user.js.txt](https://github.com/davidmz/apng-chrome/files/243472/apng.user.js.txt)
here is a user.js version created with your other project apng-canvas.
you can make extension from it. (I am not good at making crome extensions) just rename the attached file and replace the txt extention and test it on chrome.

**Comment by Telespentry** [comment]
It seems canvas.toBlock has been added to chrome. Think it will work?

**Comment by davidmz** [comment]
And finally it is fixed in v3 🎉🎉🎉
